server:
    port: 8070

eureka:
    instance:
        hostname: localhost
    client:
        service-url:
 #           defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
            defaultZone: http://localhost:8761/eureka/
application:
    config:
        students-url: http://localhost:8222/api/v1/students
spring:
    application:
        name: school
    config:
        import: optional:configserver:http://localhost:8888/

    datasource:
#        driver-class-name: org.postgresql.Driver
        driver-class-name: org.h2.Driver
#        url: jdbc:postgresql://localhost:5432/schools
        url: jdbc:h2:mem:students
        username: sa
#        username: username
        password: password


    jpa:
        hibernate:
            ddl-auto: create
        database: postgresql
#        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database-platform: org.hibernate.dialect.H2Dialect
