eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      #           defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8090

spring:
  datasource:
    #        driver-class-name: org.postgresql.Driver
    driver-class-name: org.h2.Driver
    #        url: jdbc:postgresql://localhost:5432/students
    url: jdbc:h2:mem:students
    username: sa
    #        username: username
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    #        database-platform: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.H2Dialect

management:
  tracing:
    sampling:
      probability: 1.0
